#!/bin/bash

for m in `qdbus | egrep -i 'org.mpris.MediaPlayer2|plasma-browser-integration'` ; do
	if [[ `qdbus $m /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlaybackStatus` == 'Playing' ]]; then
        	break
	fi
done

qdbus $m /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
